=== MagieGubi/3.Klasse/INSY/Insy_XML-Schema/XML/book.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="book">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="author">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="given-name" type="xs:string"/>
                            <xs:element name="middle-name" type="xs:string" minOccurs="0"/>
                            <xs:element name="last-name" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="print" type="xs:string"/>
                <xs:element name="pages" type="xs:positiveInteger"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="literature" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="symbol" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MagieGubi/3.Klasse/INSY/Insy_XML-Schema/XML/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="book.xsd">
    <title>Moby Dick</title>
    <author>
        <given-name>Herman</given-name>
        <middle-name>J. L.</middle-name>
        <last-name>Melville</last-name>
    </author>
    <print>5-5-1927</print>
    <pages>814</pages>
    <description>
Das erzhlerische Rueckgrat des Romans ist
die schicksalhafte Fahrt des Walfangschiffes
Pequod, dessen Kapitaen Ahab mit blindem Hass
den weissen Pottwal Moby Dick jagt, der ihm
ein Bein abgerissen hat.
    </description>
    <literature>
        <symbol>
    Ahabs Jagd auf den Weissen Wal steht im
    Widerspruch zu den materiellen Interessen
    von Mannschaft und Eignern. Dem Ersten
    Maat Starbuck erscheint Ahabs Rachsucht
    gegen das unvernuenftige Tier Moby Dick
    gotteslaesterlich.
        </symbol>
    </literature>
</book>
