=== MagieGubi/3.Klasse/INSY/Insy_XML-Schema/XML/euro.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="euro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="teams">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="team" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="player" type="xs:string" maxOccurs="unbounded"/>
                <xs:element name="qualifying">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="group" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="team-play" type="xs:string" maxOccurs="unbounded"/>
                                        <xs:element name="news" type="xs:string" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MagieGubi/3.Klasse/INSY/Insy_XML-Schema/XML/euro.xml
<?xml version="1.0" encoding="UTF-8" ?>
<euro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="euro.xsd">
    <teams>
        <team>Schweizer Team</team>
        <team>France</team>
    </teams>
    <player>Gareth Bale</player>
    <player>Jamie Vardy</player>
    <qualifying>
        <group>
            <team-play>FRA</team-play>
            <team-play>SUI</team-play>
            <news>The last match in Group A ended</news>
        </group>
        <group>
            <team-play>RUS</team-play>
            <team-play>GER</team-play>
            <team-play>JAP</team-play>
        </group>
    </qualifying>
</euro>
